import { Complaint } from './types';

export const mockComplaints: Complaint[] = [
  {
    id: 'JZ-2025-001',
    title: 'Врач был невнимателен',
    description: 'Врач провел приём очень быстро, не ответил на мои вопросы о побочных эффектах. Чувствовал себя спешащим и невнимательным.',
    category: 'Поведение персонала',
    priority: 'high',
    status: 'new',
    sentiment: 'negative',
    sentimentScore: 92,
    createdAt: '15 ноября 2025, 14:32',
    robotLocation: 'Кабинет 304, корпус А',
    actionHistory: [
      { timestamp: '15 ноября, 14:32', action: 'Жалоба получена от робота' },
    ],
  },
  {
    id: 'JZ-2025-002',
    title: 'Очень длинная очередь',
    description: 'Пришлось ждать 2 часа перед приёмом. Это неприемлемо для медицинского учреждения. Время ценно.',
    category: 'Организация процесса',
    priority: 'critical',
    status: 'in_progress',
    sentiment: 'negative',
    sentimentScore: 95,
    createdAt: '15 ноября 2025, 13:15',
    robotLocation: 'Регистратура, корпус B',
    assignedTo: 'Иван Петров',
    actionHistory: [
      { timestamp: '15 ноября, 13:15', action: 'Жалоба получена от робота' },
      { timestamp: '15 ноября, 14:00', actor: 'Иван Петров', action: 'Жалоба назначена' },
    ],
  },
  {
    id: 'JZ-2025-003',
    title: 'Хороший опыт посещения',
    description: 'Персонал был очень вежлив и внимателен. Врач хорошо объяснил мой диагноз и ответил на все вопросы.',
    category: 'Поведение персонала',
    priority: 'low',
    status: 'resolved',
    sentiment: 'positive',
    sentimentScore: 15,
    createdAt: '14 ноября 2025, 10:20',
    robotLocation: 'Кабинет 201, корпус А',
    assignedTo: 'Мария Иванова',
    resolvedAt: '14 ноября 2025, 15:45',
    adminResponse: 'Спасибо за добрые слова! Мы очень рады, что вам понравилось обслуживание.',
    actionHistory: [
      { timestamp: '14 ноября, 10:20', action: 'Жалоба получена от робота' },
      { timestamp: '14 ноября, 11:30', actor: 'Мария Иванова', action: 'Жалоба назначена' },
      { timestamp: '14 ноября, 15:45', actor: 'Мария Иванова', action: 'Ответ отправлен' },
      { timestamp: '14 ноября, 16:00', action: 'Жалоба закрыта' },
    ],
  },
  {
    id: 'JZ-2025-004',
    title: 'Проблема с назначением',
    description: 'Был назначен неправильный препарат. Пришлось вернуться в поликлинику для исправления. Это привело к дополнительным затратам.',
    category: 'Качество обслуживания',
    priority: 'critical',
    status: 'in_progress',
    sentiment: 'negative',
    sentimentScore: 88,
    createdAt: '14 ноября 2025, 15:45',
    robotLocation: 'Кабинет 150, корпус B',
    assignedTo: 'Алексей Сидоров',
    actionHistory: [
      { timestamp: '14 ноября, 15:45', action: 'Жалоба получена от робота' },
      { timestamp: '14 ноября, 16:30', actor: 'Алексей Сидоров', action: 'Жалоба назначена' },
    ],
  },
  {
    id: 'JZ-2025-005',
    title: 'Грязное помещение',
    description: 'Кабинет врача был грязный и неудобный. Гигиена на низком уровне. На полу были грязь и следы.',
    category: 'Условия содержания',
    priority: 'high',
    status: 'resolved',
    sentiment: 'negative',
    sentimentScore: 85,
    createdAt: '13 ноября 2025, 09:30',
    robotLocation: 'Кабинет 305, корпус А',
    assignedTo: 'Елена Волкова',
    resolvedAt: '13 ноября 2025, 17:00',
    adminResponse: 'Мы принесли извинения и провели полную санитарную обработку кабинета.',
    actionHistory: [
      { timestamp: '13 ноября, 09:30', action: 'Жалоба получена от робота' },
      { timestamp: '13 ноября, 10:00', actor: 'Елена Волкова', action: 'Жалоба назначена' },
      { timestamp: '13 ноября, 14:00', action: 'Кабинет очищен и санирован' },
      { timestamp: '13 ноября, 16:30', actor: 'Елена Волкова', action: 'Ответ отправлен' },
      { timestamp: '13 ноября, 17:00', action: 'Жалоба закрыта' },
    ],
  },
  {
    id: 'JZ-2025-006',
    title: 'Нейтральный опыт',
    description: 'Всё прошло стандартно. Ничего особенного, ничего плохого. Обычное обслуживание.',
    category: 'Общая информация',
    priority: 'low',
    status: 'resolved',
    sentiment: 'neutral',
    sentimentScore: 50,
    createdAt: '12 ноября 2025, 14:00',
    robotLocation: 'Кабинет 102, корпус B',
    resolvedAt: '12 ноября 2025, 16:00',
    actionHistory: [
      { timestamp: '12 ноября, 14:00', action: 'Жалоба получена от робота' },
      { timestamp: '12 ноября, 16:00', action: 'Жалоба закрыта' },
    ],
  },
  {
    id: 'JZ-2025-007',
    title: 'Оборудование устарело',
    description: 'Медицинское оборудование выглядит очень старым и требует модернизации. Больше не соответствует современным стандартам.',
    category: 'Оборудование',
    priority: 'medium',
    status: 'new',
    sentiment: 'negative',
    sentimentScore: 72,
    createdAt: '11 ноября 2025, 11:22',
    robotLocation: 'УЗИ кабинет, корпус А',
    actionHistory: [
      { timestamp: '11 ноября, 11:22', action: 'Жалоба получена от робота' },
    ],
  },
  {
    id: 'JZ-2025-008',
    title: 'Парковка платная и дорогая',
    description: 'Плата за парковку очень дорогая. Это создает дополнительные сложности для пациентов и их семей.',
    category: 'Условия содержания',
    priority: 'low',
    status: 'new',
    sentiment: 'negative',
    sentimentScore: 60,
    createdAt: '10 ноября 2025, 16:05',
    robotLocation: 'Паркинг, уровень 1',
    actionHistory: [
      { timestamp: '10 ноября, 16:05', action: 'Жалоба получена от робота' },
    ],
  },
  {
    id: 'JZ-2025-009',
    title: 'Отличная компетентность врача',
    description: 'Врач показал высокий уровень компетентности и профессионализма. Все объяснил понятно. Очень доволен приёмом.',
    category: 'Поведение персонала',
    priority: 'low',
    status: 'resolved',
    sentiment: 'positive',
    sentimentScore: 25,
    createdAt: '9 ноября 2025, 13:40',
    robotLocation: 'Кабинет 203, корпус B',
    resolvedAt: '9 ноября 2025, 14:30',
    actionHistory: [
      { timestamp: '9 ноября, 13:40', action: 'Жалоба получена от робота' },
      { timestamp: '9 ноября, 14:30', action: 'Жалоба закрыта' },
    ],
  },
  {
    id: 'JZ-2025-010',
    title: 'Проблема с расписанием',
    description: 'Невозможно записаться на приём в удобное время. Расписание очень неудобное. Нет вечерних часов приёма.',
    category: 'Организация процесса',
    priority: 'medium',
    status: 'in_progress',
    sentiment: 'negative',
    sentimentScore: 75,
    createdAt: '8 ноября 2025, 10:15',
    robotLocation: 'Регистратура, корпус А',
    assignedTo: 'Петр Ромов',
    actionHistory: [
      { timestamp: '8 ноября, 10:15', action: 'Жалоба получена от робота' },
      { timestamp: '8 ноября, 11:00', actor: 'Петр Ромов', action: 'Жалоба назначена' },
    ],
  },
  {
    id: 'JZ-2025-011',
    title: 'Чистота и порядок',
    description: 'Учреждение очень чистое и хорошо организовано. Отличные условия. Всё сияет чистотой.',
    category: 'Условия содержания',
    priority: 'low',
    status: 'resolved',
    sentiment: 'positive',
    sentimentScore: 20,
    createdAt: '7 ноября 2025, 12:30',
    robotLocation: 'Холл приёма, корпус B',
    resolvedAt: '7 ноября 2025, 13:00',
    actionHistory: [
      { timestamp: '7 ноября, 12:30', action: 'Жалоба получена от робота' },
      { timestamp: '7 ноября, 13:00', action: 'Жалоба закрыта' },
    ],
  },
  {
    id: 'JZ-2025-012',
    title: 'Рецепция не помогла',
    description: 'Сотрудники рецепции были неведомы помощи. Пришлось самостоятельно разбираться с документами и процедурами.',
    category: 'Поведение персонала',
    priority: 'medium',
    status: 'new',
    sentiment: 'negative',
    sentimentScore: 80,
    createdAt: '6 ноября 2025, 15:50',
    robotLocation: 'Рецепция, корпус А',
    actionHistory: [
      { timestamp: '6 ноября, 15:50', action: 'Жалоба получена от робота' },
    ],
  },
  {
    id: 'JZ-2025-013',
    title: 'Некорректное поведение администратора',
    description: 'Администратор был груб и невежлив. Не хотел решать проблему. Это очень расстроило меня.',
    category: 'Поведение персонала',
    priority: 'critical',
    status: 'in_progress',
    sentiment: 'negative',
    sentimentScore: 93,
    createdAt: '5 ноября 2025, 09:20',
    robotLocation: 'Кабинет начальника, корпус А',
    assignedTo: 'Ольга Кузнецова',
    actionHistory: [
      { timestamp: '5 ноября, 09:20', action: 'Жалоба получена от робота' },
      { timestamp: '5 ноября, 10:00', actor: 'Ольга Кузнецова', action: 'Жалоба назначена' },
    ],
  },
  {
    id: 'JZ-2025-014',
    title: 'Быстрое и эффективное обслуживание',
    description: 'Приём прошёл быстро и эффективно. Врач всё проверил, ответил на вопросы. Очень доволен временем приёма.',
    category: 'Качество обслуживания',
    priority: 'low',
    status: 'resolved',
    sentiment: 'positive',
    sentimentScore: 18,
    createdAt: '4 ноября 2025, 11:45',
    robotLocation: 'Кабинет 215, корпус B',
    resolvedAt: '4 ноября 2025, 12:30',
    actionHistory: [
      { timestamp: '4 ноября, 11:45', action: 'Жалоба получена от робота' },
      { timestamp: '4 ноября, 12:30', action: 'Жалоба закрыта' },
    ],
  },
  {
    id: 'JZ-2025-015',
    title: 'Неправильная информация в документах',
    description: 'В выданных документах была ошибка в диагнозе. Пришлось переделывать документы. Это вызвало дополнительные трудности.',
    category: 'Администрирование',
    priority: 'high',
    status: 'new',
    sentiment: 'negative',
    sentimentScore: 82,
    createdAt: '3 ноября 2025, 14:10',
    robotLocation: 'Регистратура, корпус B',
    actionHistory: [
      { timestamp: '3 ноября, 14:10', action: 'Жалоба получена от робота' },
    ],
  },
];
